import { supabaseAdmin } from '@/lib/supabase/server'
import { format } from 'date-fns'

/**
 * Deal Export & Sharing System
 * Supports: PDF, Excel, CSV, Email, Calendar, Shareable Links
 */

export class DealExporter {
  // Generate PDF report
  static async generatePDFReport(dealIds: string[], title: string = 'Disney Deals Report') {
    const deals = await this.fetchDeals(dealIds)
    
    // PDF generation would use a library like puppeteer or pdfkit
    // For now, return HTML that can be converted to PDF
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${title}</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; }
          h1 { color: #0063B2; border-bottom: 3px solid #FFB900; padding-bottom: 10px; }
          .deal { border: 1px solid #E5E7EB; border-radius: 8px; padding: 20px; margin-bottom: 20px; }
          .deal-header { display: flex; justify-content: space-between; margin-bottom: 15px; }
          .deal-title { font-size: 18px; font-weight: bold; color: #111827; }
          .discount-badge { background: #EF4444; color: white; padding: 8px 16px; border-radius: 6px; font-weight: bold; }
          .deal-details { margin-top: 15px; }
          .detail-row { margin: 8px 0; }
          .detail-label { font-weight: 600; color: #6B7280; }
          .footer { margin-top: 40px; text-align: center; color: #6B7280; font-size: 12px; }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <p>Generated: ${format(new Date(), 'MMMM d, yyyy h:mm a')}</p>
        
        ${deals.map(deal => `
          <div class="deal">
            <div class="deal-header">
              <div class="deal-title">${deal.title}</div>
              ${deal.discount_percentage ? `<div class="discount-badge">${deal.discount_percentage}% OFF</div>` : ''}
            </div>
            
            <div class="deal-details">
              ${deal.resort ? `<div class="detail-row"><span class="detail-label">Resort:</span> ${deal.resort.name}</div>` : ''}
              ${deal.deal_code ? `<div class="detail-row"><span class="detail-label">Promo Code:</span> <strong>${deal.deal_code}</strong></div>` : ''}
              <div class="detail-row"><span class="detail-label">Valid Dates:</span> ${deal.travel_valid_from} to ${deal.travel_valid_to}</div>
              ${deal.booking_deadline ? `<div class="detail-row"><span class="detail-label">Book By:</span> ${deal.booking_deadline}</div>` : ''}
              ${deal.minimum_nights ? `<div class="detail-row"><span class="detail-label">Minimum Nights:</span> ${deal.minimum_nights}</div>` : ''}
              ${deal.source_url ? `<div class="detail-row"><span class="detail-label">Source:</span> <a href="${deal.source_url}">${deal.source_url}</a></div>` : ''}
            </div>
          </div>
        `).join('')}
        
        <div class="footer">
          <p>Generated by Disney Deal Tracker | Powered by Javari AI</p>
          <p>Visit https://crav-disney-deal-tracker.vercel.app for more deals</p>
        </div>
      </body>
      </html>
    `
    
    return { html, filename: `${title.replace(/\s+/g, '_')}_${format(new Date(), 'yyyyMMdd')}.pdf` }
  }
  
  // Generate CSV export
  static async generateCSV(dealIds: string[]) {
    const deals = await this.fetchDeals(dealIds)
    
    const headers = [
      'Title',
      'Resort',
      'Discount %',
      'Promo Code',
      'Valid From',
      'Valid To',
      'Booking Deadline',
      'Min Nights',
      'Source URL'
    ]
    
    const rows = deals.map(deal => [
      deal.title,
      deal.resort?.name || '',
      deal.discount_percentage || '',
      deal.deal_code || '',
      deal.travel_valid_from,
      deal.travel_valid_to,
      deal.booking_deadline || '',
      deal.minimum_nights || '',
      deal.source_url || ''
    ])
    
    const csv = [
      headers.join(','),
      ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
    ].join('\n')
    
    return { csv, filename: `disney_deals_${format(new Date(), 'yyyyMMdd')}.csv` }
  }
  
  // Generate Excel-compatible format
  static async generateExcel(dealIds: string[]) {
    // Similar to CSV but with additional formatting metadata
    // Would use a library like exceljs in production
    return this.generateCSV(dealIds)
  }
  
  // Generate calendar event (iCal format)
  static async generateCalendarEvents(dealIds: string[]) {
    const deals = await this.fetchDeals(dealIds)
    
    const events = deals.map(deal => {
      const bookingDeadline = deal.booking_deadline ? new Date(deal.booking_deadline) : null
      const validTo = new Date(deal.valid_to)
      
      return `
BEGIN:VEVENT
UID:${deal.id}@disney-deal-tracker
DTSTAMP:${this.formatICalDate(new Date())}
DTSTART:${this.formatICalDate(bookingDeadline || validTo)}
SUMMARY:${deal.title}
DESCRIPTION:${deal.description || ''}\n\nPromo Code: ${deal.deal_code || 'N/A'}\nValid: ${deal.travel_valid_from} to ${deal.travel_valid_to}\nSource: ${deal.source_url}
URL:${deal.source_url}
STATUS:CONFIRMED
END:VEVENT
      `.trim()
    })
    
    const ical = `
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Disney Deal Tracker//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Disney Deals
X-WR-TIMEZONE:America/New_York
${events.join('\n')}
END:VCALENDAR
    `.trim()
    
    return { ical, filename: `disney_deals_${format(new Date(), 'yyyyMMdd')}.ics` }
  }
  
  // Generate shareable link
  static async generateShareLink(dealIds: string[]) {
    // Create a share record in database
    const shareId = this.generateShortId()
    
    const { data, error } = await supabaseAdmin
      .from('deal_shares')
      .insert([{
        share_id: shareId,
        deal_ids: dealIds,
        expires_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString() // 30 days
      }])
      .select()
      .single()
    
    if (error) throw error
    
    return {
      url: `https://crav-disney-deal-tracker.vercel.app/share/${shareId}`,
      expires: format(new Date(data.expires_at), 'MMMM d, yyyy')
    }
  }
  
  // Generate email summary
  static async generateEmailSummary(dealIds: string[], recipientEmail?: string) {
    const deals = await this.fetchDeals(dealIds)
    
    const emailHTML = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #0063B2 0%, #004a8a 100%); color: white; padding: 30px 20px; text-align: center; border-radius: 8px 8px 0 0; }
          .deal { background: #F9FAFB; border-radius: 8px; padding: 20px; margin: 20px 0; border-left: 4px solid #0063B2; }
          .deal-title { font-size: 18px; font-weight: bold; color: #111827; margin-bottom: 10px; }
          .discount-badge { background: #EF4444; color: white; padding: 6px 12px; border-radius: 6px; display: inline-block; font-weight: bold; margin-bottom: 10px; }
          .promo-code { background: white; border: 2px dashed #0063B2; border-radius: 6px; padding: 12px; margin: 10px 0; text-align: center; }
          .promo-code code { font-family: 'Courier New', monospace; font-size: 20px; font-weight: bold; color: #0063B2; }
          .btn { display: inline-block; background: #0063B2; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; margin-top: 10px; }
          .footer { text-align: center; color: #6B7280; font-size: 12px; margin-top: 40px; padding-top: 20px; border-top: 1px solid #E5E7EB; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>🏰 Your Disney Deals</h1>
            <p>Handpicked by Javari AI</p>
          </div>
          
          ${deals.map(deal => `
            <div class="deal">
              <div class="deal-title">${deal.title}</div>
              ${deal.discount_percentage ? `<div class="discount-badge">${deal.discount_percentage}% OFF</div>` : ''}
              
              ${deal.resort ? `<p><strong>Resort:</strong> ${deal.resort.name}</p>` : ''}
              
              ${deal.deal_code ? `
                <div class="promo-code">
                  <div style="font-size: 12px; color: #6B7280; margin-bottom: 6px;">PROMO CODE</div>
                  <code>${deal.deal_code}</code>
                </div>
              ` : ''}
              
              <p><strong>Valid Travel:</strong> ${deal.travel_valid_from} to ${deal.travel_valid_to}</p>
              ${deal.booking_deadline ? `<p><strong>Book By:</strong> ${deal.booking_deadline}</p>` : ''}
              
              <a href="${deal.source_url}" class="btn">Book Now</a>
            </div>
          `).join('')}
          
          <div class="footer">
            <p>Generated by Disney Deal Tracker | Powered by Javari AI</p>
            <p><a href="https://crav-disney-deal-tracker.vercel.app">View More Deals</a></p>
          </div>
        </div>
      </body>
      </html>
    `
    
    return { html: emailHTML, text: this.stripHTML(emailHTML) }
  }
  
  // Helper: Fetch deals with all details
  private static async fetchDeals(dealIds: string[]) {
    const { data: deals } = await supabaseAdmin
      .from('deals')
      .select(`
        *,
        resort:resorts(*),
        score:deal_scores(*)
      `)
      .in('id', dealIds)
    
    return deals || []
  }
  
  // Helper: Format date for iCal
  private static formatICalDate(date: Date): string {
    return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'
  }
  
  // Helper: Generate short ID
  private static generateShortId(): string {
    return Math.random().toString(36).substring(2, 10)
  }
  
  // Helper: Strip HTML tags
  private static stripHTML(html: string): string {
    return html.replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim()
  }
}

export default DealExporter
